---
- name: check for a ceph mon socket
  command: find {{ rbd_client_admin_socket_path }} -type s -iname {{ cluster }}-mon*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: mon_socket_list
  when:
    - inventory_hostname in groups.get(mon_group_name, [])

- name: check if the ceph mon socket is in-use
  command: fuser --silent {{ item }}
  changed_when: false
  failed_when: false
  check_mode: no
  register: mon_socket
  when:
    - inventory_hostname in groups.get(mon_group_name, [])
  with_items: "{{ mon_socket_list.stdout_lines }}"

- name: remove ceph mon socket if exists and not used by a process
  file:
    name: "{{ item.cmd[-1] }}"
    state: absent
  when:
    - inventory_hostname in groups.get(mon_group_name, [])
    - item.rc != 0
  with_items: "{{ mon_socket.results }}"
  loop_control:
    label: "{{ item.cmd[-1] }}"

- name: check for a ceph osd socket
  command: find {{ rbd_client_admin_socket_path }} -type s -iname {{ cluster }}-osd*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_socket_list
  when:
    - inventory_hostname in groups.get(osd_group_name, [])

- name: check if the ceph osd socket is in-use
  command: fuser --silent {{ item }}
  changed_when: false
  failed_when: false
  check_mode: no
  register: osd_socket
  when:
    - inventory_hostname in groups.get(osd_group_name, [])
  with_items: "{{ osd_socket_list.stdout_lines }}"

- name: remove ceph osd socket if exists and not used by a process
  file:
    name: "{{ item.cmd[-1] }}"
    state: absent
  when:
    - inventory_hostname in groups.get(osd_group_name, [])
    - item.rc != 0
  with_items: "{{ osd_socket.results }}"
  loop_control:
    label: "{{ item.cmd[-1] }}"

- name: check for a ceph mds socket
  command: find {{ rbd_client_admin_socket_path }} -type s -iname {{ cluster }}-mds*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: mds_socket_list
  when:
    - inventory_hostname in groups.get(mds_group_name, [])

- name: check if the ceph mds socket is in-use
  command: fuser --silent {{ item }}
  changed_when: false
  failed_when: false
  check_mode: no
  register: mds_socket
  when:
    - inventory_hostname in groups.get(mds_group_name, [])
  with_items: "{{ mds_socket_list.stdout_lines }}"

- name: remove ceph mds socket if exists and not used by a process
  file:
    name: "{{ item.cmd[-1] }}"
    state: absent
  when:
    - inventory_hostname in groups.get(mds_group_name, [])
    - item.rc != 0
  with_items: "{{ mds_socket.results }}"
  loop_control:
    label: "{{ item.cmd[-1] }}"

- name: check for a ceph rgw socket
  command: find {{ rbd_client_admin_socket_path }} -type s -iname {{ cluster }}-client.rgw*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: rgw_socket_list
  when:
    - inventory_hostname in groups.get(rgw_group_name, [])

- name: check if the ceph rgw socket is in-use
  command: fuser --silent {{ item }}
  changed_when: false
  failed_when: false
  check_mode: no
  register: rgw_socket
  when:
    - inventory_hostname in groups.get(rgw_group_name, [])
  with_items: "{{ rgw_socket_list.stdout_lines }}"

- name: remove ceph rgw socket if exists and not used by a process
  file:
    name: "{{ item.cmd[-1] }}"
    state: absent
  when:
    - inventory_hostname in groups.get(rgw_group_name, [])
    - item.rc != 0
  with_items: "{{ rgw_socket.results }}"
  loop_control:
    label: "{{ item.cmd[-1] }}"

- name: check for a ceph mgr socket
  command: find {{ rbd_client_admin_socket_path }} -type s -iname {{ cluster }}-mgr*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: mgr_socket_list
  when:
    - inventory_hostname in groups.get(mgr_group_name, [])

- name: check if the ceph mgr socket is in-use
  command: fuser --silent {{ item }}
  changed_when: false
  failed_when: false
  check_mode: no
  register: mgr_socket
  when:
    - inventory_hostname in groups.get(mgr_group_name, [])
  with_items: "{{ mgr_socket_list.stdout_lines }}"

- name: remove ceph mgr socket if exists and not used by a process
  file:
    name: "{{ item.cmd[-1] }}"
    state: absent
  when:
    - inventory_hostname in groups.get(mgr_group_name, [])
    - item.rc != 0
  with_items: "{{ mgr_socket.results }}"
  loop_control:
    label: "{{ item.cmd[-1] }}"

- name: check for a ceph rbd mirror socket
  command: find {{ rbd_client_admin_socket_path }} -type s -iname {{ cluster }}-client.rbd-mirror*.asok
  changed_when: false
  failed_when: false
  check_mode: no
  register: rbd_mirror_socket_list
  when:
    - inventory_hostname in groups.get(rbdmirror_group_name, [])

- name: check if the ceph rbd mirror socket is in-use
  command: fuser --silent {{ item }}
  changed_when: false
  failed_when: false
  check_mode: no
  register: rbd_mirror_socket
  when:
    - inventory_hostname in groups.get(rbdmirror_group_name, [])
  with_items: "{{ rbd_mirror_socket_list.stdout_lines }}"

- name: remove ceph rbd mirror socket if exists and not used by a process
  file:
    name: "{{ item.cmd[-1] }}"
    state: absent
  when:
    - inventory_hostname in groups.get(rbdmirror_group_name, [])
    - item.rc != 0
  with_items: "{{ rbd_mirror_socket.results }}"
  loop_control:
    label: "{{ item.cmd[-1] }}"

- name: check for a ceph nfs ganesha socket
  command: stat --printf=%n /var/run/ganesha.pid
  changed_when: false
  failed_when: false
  check_mode: no
  register: nfs_socket_stat
  when:
    - inventory_hostname in groups.get(nfs_group_name, [])

- name: check if the ceph nfs ganesha socket is in-use
  command: fuser --silent {{ nfs_socket_stat.stdout }}
  changed_when: false
  failed_when: false
  check_mode: no
  register: nfs_socket
  when:
    - inventory_hostname in groups.get(nfs_group_name, [])
    - nfs_socket_stat.rc == 0

- name: remove ceph nfs ganesha socket if exists and not used by a process
  file:
    name: "{{ nfs_socket_stat.stdout }}"
    state: absent
  when:
    - inventory_hostname in groups.get(nfs_group_name, [])
    - nfs_socket_stat.rc == 0
    - nfs_socket.rc == 1

- name: check for a tcmu-runner
  command: "pgrep tcmu-runner"
  register: ceph_tcmu_runner_stat
  changed_when: false
  failed_when: false
  check_mode: no
  when:
    - inventory_hostname in groups.get(iscsi_gw_group_name, [])

- name: check for a rbd-target-api
  command: "pgrep rbd-target-api"
  register: ceph_rbd_target_api_stat
  changed_when: false
  failed_when: false
  check_mode: no
  when:
    - inventory_hostname in groups.get(iscsi_gw_group_name, [])

- name: check for a rbd-target-gw
  command: "pgrep name=rbd-target-gw"
  register: ceph_rbd_target_gw_stat
  changed_when: false
  failed_when: false
  check_mode: no
  when:
    - inventory_hostname in groups.get(iscsi_gw_group_name, [])

